-- ============================================================
--  DERJA — contenu initial
--  À lancer APRÈS db/schema.sql, dans Supabase → SQL Editor.
--  Relançable sans créer de doublon (on conflict do nothing).
--  136 mots · 46 phrases · 18 verbes
-- ============================================================

-- ---------- MOTS ----------
insert into public.items (kind, category, fr, arabizi, ar, note, is_seed, verified) values
  ('word', 'Salutations', 'bonjour (matin)', 'sbah lkhir', 'صباح الخير', 'kh = jota espagnole', true, false),
  ('word', 'Salutations', 'bonsoir', 'msa lkhir', 'مساء الخير', '', true, false),
  ('word', 'Salutations', 'ça va ? (à un homme)', 'wach rak ?', 'واش راك', 'r roulé, pas français', true, false),
  ('word', 'Salutations', 'ça va ? (à une femme)', 'wach raki ?', 'واش راكي', '', true, false),
  ('word', 'Salutations', 'ça va bien, Dieu merci', 'labas, hamdoulah', 'لاباس، الحمد لله', '', true, false),
  ('word', 'Salutations', 'comment tu t''appelles ?', 'wach smitek ?', 'واش سميتك', '', true, false),
  ('word', 'Salutations', 'je m''appelle…', 'smiti…', 'سميتي', '', true, false),
  ('word', 'Salutations', 'd''où viens-tu ?', 'mnin nta ?', 'منين نتَ', '', true, false),
  ('word', 'Salutations', 'je viens de France', 'rani men fransa', 'راني من فرنسا', '', true, false),
  ('word', 'Salutations', 'merci', 'sahit', 'صحيت', 'le plus algérien', true, false),
  ('word', 'Salutations', 'merci (chaleureux)', 'y3ayechek', 'يعيشك', '3 = gorge serrée', true, false),
  ('word', 'Salutations', 'de rien', 'bla jmil', 'بلا جميل', '', true, false),
  ('word', 'Salutations', 's''il te plaît', 'men fadlek', 'من فضلك', '', true, false),
  ('word', 'Salutations', 'excuse-moi', 'smahli', 'سمحلي', '', true, false),
  ('word', 'Salutations', 'oui / non', 'ih / lala', 'ايه / لالا', '', true, false),
  ('word', 'Salutations', 'd''accord, c''est vrai', 'sah', 'صح', '', true, false),
  ('word', 'Salutations', 'pas de problème', 'makach mouchkil', 'ماكاش مشكل', '', true, false),
  ('word', 'Salutations', 'au revoir', 'bslama', 'بسلامة', '', true, false),
  ('word', 'Salutations', 'à demain', 'nchoufek ghedwa', 'نشوفك غدوة', 'gh = r français', true, false),
  ('word', 'Salutations', 'bienvenue', 'mrahba', 'مرحبا', '', true, false),
  ('word', 'Famille', 'père / papa', 'baba', 'بابا', '', true, false),
  ('word', 'Famille', 'mère / maman', 'yemma', 'يما', '', true, false),
  ('word', 'Famille', 'mon frère', 'khouya', 'خويا', '', true, false),
  ('word', 'Famille', 'ma sœur', 'khti', 'ختي', '', true, false),
  ('word', 'Famille', 'grand-père', 'jeddi', 'جدي', '', true, false),
  ('word', 'Famille', 'grand-mère', 'setti', 'ستي', '', true, false),
  ('word', 'Famille', 'oncle paternel', '3ammi', 'عمي', '', true, false),
  ('word', 'Famille', 'tante paternelle', '3amti', 'عمتي', '', true, false),
  ('word', 'Famille', 'oncle maternel', 'khali', 'خالي', '', true, false),
  ('word', 'Famille', 'tante maternelle', 'khalti', 'خالتي', '', true, false),
  ('word', 'Famille', 'cousin (paternel)', 'weld 3ammi', 'ولد عمي', '', true, false),
  ('word', 'Famille', 'mon fils / ma fille', 'weldi / benti', 'ولدي / بنتي', '', true, false),
  ('word', 'Famille', 'les enfants, les gosses', 'drari', 'دراري', '', true, false),
  ('word', 'Famille', 'mari / épouse', 'rajel / mra', 'راجل / مرا', '', true, false),
  ('word', 'Famille', 'famille', '3a''ila', 'عائلة', '', true, false),
  ('word', 'Famille', 'ami', 'sahbi', 'صاحبي', '', true, false),
  ('word', 'Famille', 'voisin', 'jari', 'جاري', '', true, false),
  ('word', 'Famille', 'invité', 'dif', 'ضيف', '', true, false),
  ('word', 'Questions', 'quoi ?', 'wach ?', 'واش', '', true, false),
  ('word', 'Questions', 'qui ?', 'chkoun ?', 'شكون', '', true, false),
  ('word', 'Questions', 'où ?', 'win ?', 'وين', '', true, false),
  ('word', 'Questions', 'quand ?', 'wektach ?', 'وقتاش', '', true, false),
  ('word', 'Questions', 'pourquoi ?', '3lah ?', 'علاه', '', true, false),
  ('word', 'Questions', 'comment ?', 'kifach ?', 'كيفاش', '', true, false),
  ('word', 'Questions', 'combien ?', 'chhal ?', 'شحال', '', true, false),
  ('word', 'Questions', 'c''est quoi ça ?', 'wach hada ?', 'واش هذا', '', true, false),
  ('word', 'Questions', 'ici / là-bas', 'hna / temma', 'هنا / تما', '', true, false),
  ('word', 'Questions', 'comme ça', 'hakda', 'هكدا', '', true, false),
  ('word', 'Questions', 'mais', 'besah', 'بصح', '', true, false),
  ('word', 'Questions', 'seulement, juste', 'ghir', 'غير', '« rhir »', true, false),
  ('word', 'Questions', 'avec / sans', 'm3a / bla', 'مع / بلا', '', true, false),
  ('word', 'Questions', 'je ne comprends pas', 'ma fhemtch', 'ما فهمتش', '', true, false),
  ('word', 'Questions', 'je ne sais pas', 'ma na3refch', 'ما نعرفش', '', true, false),
  ('word', 'Questions', 'parle doucement', 'hder bechwiya', 'هدر بشوية', '', true, false),
  ('word', 'Questions', 'répète', '3awed', 'عاود', '', true, false),
  ('word', 'Questions', 'qu''est-ce que ça veut dire ?', 'wach ma3natha ?', 'واش معناها', '', true, false),
  ('word', 'Verbes', 'je veux / j''aime', 'nheb', 'نحب', 'h très soufflé', true, false),
  ('word', 'Verbes', 'je vais', 'nroh', 'نروح', '', true, false),
  ('word', 'Verbes', 'je viens', 'nji', 'نجي', '', true, false),
  ('word', 'Verbes', 'je mange', 'nakoul', 'ناكل', '', true, false),
  ('word', 'Verbes', 'je bois', 'nechreb', 'نشرب', '', true, false),
  ('word', 'Verbes', 'je regarde / je vois', 'nchouf', 'نشوف', '', true, false),
  ('word', 'Verbes', 'j''écoute / j''entends', 'nesma3', 'نسمع', '', true, false),
  ('word', 'Verbes', 'je parle', 'nehder', 'نهدر', '', true, false),
  ('word', 'Verbes', 'je comprends', 'nefhem', 'نفهم', '', true, false),
  ('word', 'Verbes', 'je sais', 'na3ref', 'نعرف', '', true, false),
  ('word', 'Verbes', 'je fais', 'ndir', 'ندير', '', true, false),
  ('word', 'Verbes', 'je donne', 'n3ti', 'نعطي', '', true, false),
  ('word', 'Verbes', 'je prends', 'nakhod', 'ناخذ', '', true, false),
  ('word', 'Verbes', 'j''attends', 'nstenna', 'نستنى', '', true, false),
  ('word', 'Verbes', 'j''ai besoin de', 'nhtaj', 'نحتاج', '', true, false),
  ('word', 'Verbes', 'je travaille', 'nekhdem', 'نخدم', '', true, false),
  ('word', 'Verbes', 'je dors', 'nerqod', 'نرقد', '', true, false),
  ('word', 'Verbes', 'je pars / je marche', 'nemchi', 'نمشي', '', true, false),
  ('word', 'Verbes', 'j''ai', '3andi', 'عندي', '', true, false),
  ('word', 'Verbes', 'il y a / il n''y a pas', 'kayen / makanch', 'كاين / ماكاش', '', true, false),
  ('word', 'Nombres & temps', 'un, deux, trois', 'wahed, zouj, tlata', 'واحد، زوج، ثلاثة', '', true, false),
  ('word', 'Nombres & temps', 'quatre, cinq, six', 'reb3a, khamsa, setta', 'أربعة، خمسة، ستة', '', true, false),
  ('word', 'Nombres & temps', 'sept, huit, neuf', 'seb3a, tmenya, tes3a', 'سبعة، ثمنية، تسعة', '', true, false),
  ('word', 'Nombres & temps', 'dix / vingt / cent', '3achra / 3achrin / mya', 'عشرة / عشرين / مية', '', true, false),
  ('word', 'Nombres & temps', 'aujourd''hui', 'lyoum', 'اليوم', '', true, false),
  ('word', 'Nombres & temps', 'demain / hier', 'ghedwa / lbareh', 'غدوة / البارح', '', true, false),
  ('word', 'Nombres & temps', 'maintenant', 'drok', 'دروك', '', true, false),
  ('word', 'Nombres & temps', 'avant / après', 'qbel / men be3d', 'قبل / من بعد', '', true, false),
  ('word', 'Nombres & temps', 'matin / soir / nuit', 'sbah / 3chiya / lil', 'صباح / عشية / ليل', '', true, false),
  ('word', 'Nombres & temps', 'semaine / mois / année', 'jem3a / chher / 3am', 'جمعة / شهر / عام', '', true, false),
  ('word', 'Nombres & temps', 'quelle heure est-il ?', 'chhal fessa3a ?', 'شحال في الساعة', '', true, false),
  ('word', 'Nourriture', 'eau', 'lma', 'الماء', '', true, false),
  ('word', 'Nourriture', 'pain', 'khobz', 'خبز', '', true, false),
  ('word', 'Nourriture', 'viande / poulet', 'lhem / djaj', 'لحم / دجاج', '', true, false),
  ('word', 'Nourriture', 'poisson', 'hout', 'حوت', '', true, false),
  ('word', 'Nourriture', 'légumes / fruits', 'khodra / fakya', 'خضرة / فاكية', '', true, false),
  ('word', 'Nourriture', 'sel / sucre / huile', 'melh / sukkar / zit', 'ملح / سكر / زيت', '', true, false),
  ('word', 'Nourriture', 'thé / café / lait', 'tay / qahwa / hlib', 'تاي / قهوة / حليب', 'qahwa souvent dit « gahwa »', true, false),
  ('word', 'Nourriture', 'repas, nourriture', 'makla', 'ماكلة', '', true, false),
  ('word', 'Nourriture', 'petit-déj / déjeuner / dîner', 'ftour / ghda / 3cha', 'فطور / غدا / عشا', '', true, false),
  ('word', 'Nourriture', 'c''est délicieux', 'bnin', 'بنين', '', true, false),
  ('word', 'Nourriture', 'j''ai faim', 'rani jya3n', 'راني جيعان', '', true, false),
  ('word', 'Nourriture', 'j''ai soif', 'rani 3atchan', 'راني عطشان', '', true, false),
  ('word', 'Nourriture', 'je suis rassasié', 'chba3t', 'شبعت', '', true, false),
  ('word', 'Voyage', 'taxi / voiture', 'taxi / tomobil', 'طاكسي / طوموبيل', '', true, false),
  ('word', 'Voyage', 'route / chemin', 'triq', 'طريق', '', true, false),
  ('word', 'Voyage', 'aéroport / gare', 'matar / mahatta', 'مطار / محطة', '', true, false),
  ('word', 'Voyage', 'marché / boutique', 'souq / hanout', 'سوق / حانوت', '', true, false),
  ('word', 'Voyage', 'hôtel', 'foundoq', 'فندق', '', true, false),
  ('word', 'Voyage', 'hôpital / pharmacie', 'sbitar / saydaliya', 'سبيطار / صيدلية', '', true, false),
  ('word', 'Voyage', 'banque / police', 'banka / chorta', 'بنكة / شرطة', '', true, false),
  ('word', 'Voyage', 'argent', 'flouss', 'فلوس', '', true, false),
  ('word', 'Voyage', 'combien ça coûte ?', 'b chhal ?', 'بشحال', '', true, false),
  ('word', 'Voyage', 'c''est cher', 'ghali', 'غالي', '', true, false),
  ('word', 'Voyage', 'baisse un peu le prix', 'naqes chwiya', 'نقص شوية', '', true, false),
  ('word', 'Voyage', 'emmène-moi à…', 'dini l…', 'ديني ل', '', true, false),
  ('word', 'Voyage', 'arrête-toi ici', 'weqef hna', 'وقف هنا', '', true, false),
  ('word', 'Voyage', 'où sont les toilettes ?', 'win rahom twalet ?', 'وين راهم التواليت', '', true, false),
  ('word', 'Voyage', 'je suis perdu', 'rani twedert', 'راني توضرت', '', true, false),
  ('word', 'Voyage', 'aide-moi', '3awenni', 'عاوني', '', true, false),
  ('word', 'Voyage', 'attention !', 'redd balek', 'رد بالك', '', true, false),
  ('word', 'Voyage', 'maison / chambre', 'dar / bit', 'دار / بيت', '', true, false),
  ('word', 'Voyage', 'clé / porte', 'sarout / bab', 'ساروت / باب', '', true, false),
  ('word', 'Voyage', 'téléphone', 'telifoun', 'تيليفون', '', true, false),
  ('word', 'Adjectifs', 'beaucoup / un peu', 'bezzaf / chwiya', 'بزاف / شوية', '', true, false),
  ('word', 'Adjectifs', 'bien / mauvais', 'mlih / khayeb', 'مليح / خايب', '', true, false),
  ('word', 'Adjectifs', 'facile / difficile', 'sahel / s3ib', 'ساهل / صعيب', '', true, false),
  ('word', 'Adjectifs', 'grand / petit', 'kbir / sghir', 'كبير / صغير', '', true, false),
  ('word', 'Adjectifs', 'nouveau / vieux', 'jdid / qdim', 'جديد / قديم', '', true, false),
  ('word', 'Adjectifs', 'chaud / froid', 'skhoun / bared', 'سخون / بارد', '', true, false),
  ('word', 'Adjectifs', 'beau, joli', 'chbab', 'شباب', '', true, false),
  ('word', 'Adjectifs', 'fatigué', '3ayan', 'عيان', '', true, false),
  ('word', 'Adjectifs', 'malade', 'mrid', 'مريض', '', true, false),
  ('word', 'Adjectifs', 'content', 'ferhan', 'فرحان', '', true, false),
  ('word', 'Adjectifs', 'viens ! / va !', 'arwah ! / roh !', 'أرواح / روح', '', true, false),
  ('word', 'Adjectifs', 'assieds-toi', 'oq3od', 'اقعد', '', true, false),
  ('word', 'Adjectifs', 'doucement / vite', 'bechwiya / fissa3', 'بشوية / فيسع', '', true, false),
  ('word', 'Adjectifs', 'ça suffit', 'yezzi', 'يزي', '', true, false),
  ('word', 'Adjectifs', 'patience', 'sber', 'صبر', '', true, false),
  ('word', 'Adjectifs', 'si Dieu le veut', 'inchallah', 'إن شاء الله', '', true, false)
on conflict do nothing;

-- ---------- PHRASES ----------
insert into public.items (kind, category, fr, arabizi, ar, note, cloze_index, is_seed, verified) values
  ('sentence', 'Famille', 'Comment vas-tu, maman ?', 'wach raki yemma ?', 'واش راكي يما', 'raki = forme féminine de rak', 1, true, false),
  ('sentence', 'Famille', 'Je vais bien, Dieu merci.', 'rani labas, hamdoulah', 'راني لاباس، الحمد لله', 'rani = je suis (état)', 0, true, false),
  ('sentence', 'Famille', 'Mon frère travaille à Alger.', 'khouya yekhdem fel dzayer', 'خويا يخدم في الدزاير', 'ye- = préfixe de ''il''', 1, true, false),
  ('sentence', 'Famille', 'Ma sœur est plus grande que moi.', 'khti kbira 3liya', 'ختي كبيرة عليا', 'kbira = féminin de kbir', 1, true, false),
  ('sentence', 'Famille', 'J''aime beaucoup ma famille.', 'nheb 3a''ilti bezzaf', 'نحب عائلتي بزاف', 'n- = préfixe de ''je''', 0, true, false),
  ('sentence', 'Famille', 'Où est papa ?', 'win rah baba ?', 'وين راح بابا', 'rah = il est', 1, true, false),
  ('sentence', 'Famille', 'Les enfants dorment.', 'drari raqdin', 'دراري راقدين', 'participe, pas de verbe ''être''', 1, true, false),
  ('sentence', 'Famille', 'Qu''est-ce que tu as fait aujourd''hui ?', 'wach dert lyoum ?', 'واش درت اليوم', 'dert = passé de dar (faire)', 1, true, false),
  ('sentence', 'Famille', 'Je n''ai pas mangé.', 'ma klitch', 'ما كليتش', 'négation ma…ch collée au verbe', 0, true, false),
  ('sentence', 'Famille', 'On mange ensemble ce soir.', 'naklou m3a be3dana lyoum fel3chiya', 'ناكلو مع بعضنا اليوم في العشية', 'na-…-ou = nous', 0, true, false),
  ('sentence', 'Famille', 'Viens t''asseoir avec nous.', 'arwah oq3od m3ana', 'أرواح اقعد معنا', 'arwah = impératif irrégulier de ''venir''', 0, true, false),
  ('sentence', 'Famille', 'Je t''appellerai demain.', 'rah n3aytlek ghedwa', 'راح نعيطلك غدوة', 'rah + présent = futur', 0, true, false),
  ('sentence', 'Famille', 'Tu me manques.', 'twahachtek', 'توحشتك', 'expression figée, très courante', 0, true, false),
  ('sentence', 'Famille', 'Dis bonjour à ta mère de ma part.', 'sellem 3la yemmak', 'سلم على يماك', 'sellem = impératif', 0, true, false),
  ('sentence', 'Quotidien', 'Je ne comprends pas, répète.', 'ma fhemtch, 3awed', 'ما فهمتش، عاود', '', 0, true, false),
  ('sentence', 'Quotidien', 'Parle doucement s''il te plaît.', 'hder bechwiya men fadlek', 'هدر بشوية من فضلك', 'bechwiya = doucement', 1, true, false),
  ('sentence', 'Quotidien', 'Je ne parle pas bien l''arabe.', 'ma nehderch mlih bel3arbiya', 'ما نهدرش مليح بالعربية', 'mlih = bien', 1, true, false),
  ('sentence', 'Quotidien', 'J''apprends l''arabe algérien.', 'rani naqra derja', 'راني نقرا درجة', 'naqra = j''étudie', 2, true, false),
  ('sentence', 'Quotidien', 'Comment on dit ça en arabe ?', 'kifach ngoulou hada bel3arbiya ?', 'كيفاش نقولو هذا بالعربية', 'kifach = comment', 0, true, false),
  ('sentence', 'Quotidien', 'Qu''est-ce que ça veut dire ?', 'wach ma3natha ?', 'واش معناها', '', 1, true, false),
  ('sentence', 'Quotidien', 'Je suis fatigué aujourd''hui.', 'rani 3ayan lyoum', 'راني عيان اليوم', '3ayan = fatigué', 1, true, false),
  ('sentence', 'Quotidien', 'Il fait très chaud.', 'skhoun bezzaf', 'سخون بزاف', 'bezzaf = beaucoup, très', 1, true, false),
  ('sentence', 'Quotidien', 'Je n''ai pas le temps.', 'ma3andich lwaqt', 'ماعنديش الوقت', 'ma3andich = je n''ai pas', 0, true, false),
  ('sentence', 'Quotidien', 'Attends-moi une minute.', 'stennani dqiqa', 'استناني دقيقة', '', 0, true, false),
  ('sentence', 'Quotidien', 'Ce n''est pas grave.', 'machi mouchkil', 'ماشي مشكل', 'machi = négation devant un nom', 0, true, false),
  ('sentence', 'Quotidien', 'Je veux du thé s''il te plaît.', 'nheb tay men fadlek', 'نحب تاي من فضلك', 'nheb = je veux / j''aime', 0, true, false),
  ('sentence', 'Quotidien', 'C''est délicieux !', 'hada bnin !', 'هذا بنين', '', 1, true, false),
  ('sentence', 'Quotidien', 'Il n''y a personne ici.', 'makanch hetta wahed hna', 'ماكانش حتى واحد هنا', 'makanch = il n''y a pas', 0, true, false),
  ('sentence', 'Quotidien', 'Je suis en train de travailler.', 'rani nekhdem', 'راني نخدم', 'ra- + présent = action en cours', 1, true, false),
  ('sentence', 'Quotidien', 'Hier je suis allé au marché.', 'lbareh reht lessouq', 'البارح رحت للسوق', 'reht = passé irrégulier de rah', 1, true, false),
  ('sentence', 'Voyage', 'Emmène-moi à l''aéroport.', 'dini lelmatar', 'ديني للمطار', 'dini = emmène-moi', 0, true, false),
  ('sentence', 'Voyage', 'Combien ça coûte ?', 'b chhal ?', 'بشحال', 'chhal = combien', 1, true, false),
  ('sentence', 'Voyage', 'C''est trop cher, baisse un peu.', 'ghali bezzaf, naqes chwiya', 'غالي بزاف، نقص شوية', 'ghali = cher', 0, true, false),
  ('sentence', 'Voyage', 'Arrête-toi ici s''il te plaît.', 'weqef hna men fadlek', 'وقف هنا من فضلك', 'weqef = impératif, arrête-toi', 0, true, false),
  ('sentence', 'Voyage', 'Où sont les toilettes ?', 'win rahom twalet ?', 'وين راهم التواليت', 'win = où', 0, true, false),
  ('sentence', 'Voyage', 'Je cherche une pharmacie.', 'rani nqelleb 3la saydaliya', 'راني نقلب على صيدلية', 'nqelleb 3la = je cherche', 2, true, false),
  ('sentence', 'Voyage', 'Je suis perdu, aide-moi.', 'rani twedert, 3awenni', 'راني توضرت، عاوني', '3awenni = aide-moi', 3, true, false),
  ('sentence', 'Voyage', 'Est-ce que tu parles français ?', 'tehder ferancawiya ?', 'تهدر فرنساوية', 'te- = préfixe de ''tu''', 0, true, false),
  ('sentence', 'Voyage', 'Je viens de France.', 'rani men fransa', 'راني من فرنسا', '', 2, true, false),
  ('sentence', 'Voyage', 'C''est loin d''ici ?', 'b3id men hna ?', 'بعيد من هنا', 'b3id = loin', 0, true, false),
  ('sentence', 'Voyage', 'Je voudrais réserver une chambre.', 'nheb nehjez bit', 'نحب نحجز بيت', 'deux verbes : le 2e reste au présent', 1, true, false),
  ('sentence', 'Voyage', 'À quelle heure part le bus ?', 'wektach yemchi lkar ?', 'وقتاش يمشي الكار', 'wektach = quand', 0, true, false),
  ('sentence', 'Voyage', 'Donne-moi du pain s''il te plaît.', '3tini khobz men fadlek', 'عطيني خبز من فضلك', '3tini = donne-moi', 0, true, false),
  ('sentence', 'Voyage', 'Je ne veux pas, merci.', 'ma nhebch, sahit', 'ما نحبش، صحيت', 'ma…ch autour du verbe', 0, true, false),
  ('sentence', 'Voyage', 'Tu peux m''aider ?', 'tqder t3awenni ?', 'تقدر تعاوني', 'tqder = tu peux', 0, true, false),
  ('sentence', 'Voyage', 'Où est la gare ?', 'win rahi lmahatta ?', 'وين راهي المحطة', 'rahi = féminin de rah', 2, true, false)
on conflict do nothing;

-- ---------- VERBES ----------
-- forms.present / forms.past : 8 formes dans l'ordre
-- ana, nta, nti, houwa, hiya, hna, ntouma, houma
insert into public.verbs (fr, base, ar, pattern, forms, is_seed, verified) values
  ('écrire', 'kteb', 'كتب', 'régulier', '{"present":["nekteb","tekteb","tektebi","yekteb","tekteb","nektbou","tektbou","yektbou"],"past":["ktebt","ktebt","ktebti","kteb","ketbet","ktebna","ktebtou","ketbou"]}'::jsonb, true, false),
  ('comprendre', 'fhem', 'فهم', 'régulier', '{"present":["nefhem","tefhem","tefhemi","yefhem","tefhem","nefehmou","tefehmou","yefehmou"],"past":["fhemt","fhemt","fhemti","fhem","fehmet","fhemna","fhemtou","fehmou"]}'::jsonb, true, false),
  ('boire', 'chreb', 'شرب', 'régulier', '{"present":["nechreb","techreb","techrebi","yechreb","techreb","nechorbou","techorbou","yechorbou"],"past":["chrebt","chrebt","chrebti","chreb","cherbet","chrebna","chrebtou","cherbou"]}'::jsonb, true, false),
  ('travailler', 'khdem', 'خدم', 'régulier', '{"present":["nekhdem","tekhdem","tekhdemi","yekhdem","tekhdem","nekhedmou","tekhedmou","yekhedmou"],"past":["khdemt","khdemt","khdemti","khdem","khedmet","khdemna","khdemtou","khedmou"]}'::jsonb, true, false),
  ('entendre, écouter', 'sme3', 'سمع', 'régulier', '{"present":["nesma3","tesma3","tesma3i","yesma3","tesma3","nesem3ou","tesem3ou","yesem3ou"],"past":["sme3t","sme3t","sme3ti","sme3","sem3et","sme3na","sme3tou","sem3ou"]}'::jsonb, true, false),
  ('savoir, connaître', '3ref', 'عرف', 'régulier', '{"present":["na3ref","ta3ref","ta3refi","ya3ref","ta3ref","na3erfou","ta3erfou","ya3erfou"],"past":["3reft","3reft","3refti","3ref","3erfet","3refna","3reftou","3erfou"]}'::jsonb, true, false),
  ('parler', 'hder', 'هدر', 'régulier', '{"present":["nehder","tehder","tehderi","yehder","tehder","nehedrou","tehedrou","yehedrou"],"past":["hdert","hdert","hderti","hder","hedret","hderna","hdertou","hedrou"]}'::jsonb, true, false),
  ('entrer', 'dkhel', 'دخل', 'régulier', '{"present":["nedkhel","tedkhel","tedkheli","yedkhel","tedkhel","nedekhlou","tedekhlou","yedekhlou"],"past":["dkhelt","dkhelt","dkhelti","dkhel","dekhlet","dkhelna","dkheltou","dekhlou"]}'::jsonb, true, false),
  ('sortir', 'khrej', 'خرج', 'régulier', '{"present":["nekhrej","tekhrej","tekhreji","yekhrej","tekhrej","nekherjou","tekherjou","yekherjou"],"past":["khrejt","khrejt","khrejti","khrej","kherjet","khrejna","khrejtou","kherjou"]}'::jsonb, true, false),
  ('aller', 'rah', 'راح', 'irrégulier (creux)', '{"present":["nroh","troh","trohi","yroh","troh","nrohou","trohou","yrohou"],"past":["reht","reht","rehti","rah","rahet","rehna","rehtou","rahou"]}'::jsonb, true, false),
  ('voir, regarder', 'chaf', 'شاف', 'irrégulier (creux)', '{"present":["nchouf","tchouf","tchoufi","ychouf","tchouf","nchoufou","tchoufou","ychoufou"],"past":["cheft","cheft","chefti","chaf","chafet","chefna","cheftou","chafou"]}'::jsonb, true, false),
  ('faire', 'dar', 'دار', 'irrégulier (creux)', '{"present":["ndir","tdir","tdiri","ydir","tdir","ndirou","tdirou","ydirou"],"past":["dert","dert","derti","dar","daret","derna","dertou","darou"]}'::jsonb, true, false),
  ('aimer, vouloir', 'hab', 'حب', 'irrégulier (redoublé)', '{"present":["nheb","theb","thebbi","yheb","theb","nhebbou","thebbou","yhebbou"],"past":["hbit","hbit","hbiti","hab","habet","hbina","hbitou","habou"]}'::jsonb, true, false),
  ('manger', 'kla', 'كلا', 'irrégulier (final faible)', '{"present":["nakoul","takoul","takouli","yakoul","takoul","naklou","taklou","yaklou"],"past":["klit","klit","kliti","kla","klat","klina","klitou","klaw"]}'::jsonb, true, false),
  ('venir', 'ja', 'جا', 'irrégulier (final faible)', '{"present":["nji","tji","tji","yji","tji","njiw","tjiw","yjiw"],"past":["jit","jit","jiti","ja","jat","jina","jitou","jaw"]}'::jsonb, true, false),
  ('partir, marcher', 'mcha', 'مشى', 'irrégulier (final faible)', '{"present":["nemchi","temchi","temchi","yemchi","temchi","nemchiw","temchiw","yemchiw"],"past":["mchit","mchit","mchiti","mcha","mchat","mchina","mchitou","mchaw"]}'::jsonb, true, false),
  ('lire, étudier', 'qra', 'قرا', 'irrégulier (final faible)', '{"present":["naqra","taqra","taqray","yaqra","taqra","naqraw","taqraw","yaqraw"],"past":["qrit","qrit","qriti","qra","qrat","qrina","qritou","qraw"]}'::jsonb, true, false),
  ('donner', '3ta', 'عطى', 'irrégulier (final faible)', '{"present":["n3ti","t3ti","t3ti","y3ti","t3ti","n3tiw","t3tiw","y3tiw"],"past":["3tit","3tit","3titi","3ta","3tat","3tina","3titou","3taw"]}'::jsonb, true, false)
on conflict do nothing;

-- ---------- VÉRIFICATION ----------
select 'mots' as type, count(*) from public.items where kind = 'word'
union all select 'phrases', count(*) from public.items where kind = 'sentence'
union all select 'verbes', count(*) from public.verbs;
